<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>R ile Uygulamalı Ekonometri - 4&nbsp; Nitel Açıklayıcı Değişkenli Regresyon Modelleri</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./kaynak.html" rel="next">
<link href="./regresyon_model_fonksiyon.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Nitel Açıklayıcı Değişkenli Regresyon Modelleri</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">R ile Uygulamalı Ekonometri</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Önsöz</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./surec.html" class="sidebar-item-text sidebar-link">Süreç</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./veriseti.html" class="sidebar-item-text sidebar-link">Veri Setleri</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./kutuphane.html" class="sidebar-item-text sidebar-link">Kütüphaneler</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dogrusal_regresyon_modeli.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Doğrusal Regresyon Modeli</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./francis_galton_regresyon.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Francis Galton ve Regresyon Terimi</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regresyon_model_fonksiyon.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regresyon Modellerinin Fonksiyon Yapıları</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./kukla_degisken.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Nitel Açıklayıcı Değişkenli Regresyon Modelleri</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./kaynak.html" class="sidebar-item-text sidebar-link">Yararlandığım Kaynaklar</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#ücret-modeli" id="toc-ücret-modeli" class="nav-link active" data-scroll-target="#ücret-modeli"><span class="toc-section-number">4.1</span>  Ücret Modeli</a></li>
  <li><a href="#yapısal-değişimdeki-rolü" id="toc-yapısal-değişimdeki-rolü" class="nav-link" data-scroll-target="#yapısal-değişimdeki-rolü"><span class="toc-section-number">4.2</span>  Yapısal Değişimdeki Rolü</a></li>
  <li><a href="#mevsimsel-verilerdeki-rolü" id="toc-mevsimsel-verilerdeki-rolü" class="nav-link" data-scroll-target="#mevsimsel-verilerdeki-rolü"><span class="toc-section-number">4.3</span>  Mevsimsel Verilerdeki Rolü</a></li>
  <li><a href="#parçalı-doğrusal-regresyon" id="toc-parçalı-doğrusal-regresyon" class="nav-link" data-scroll-target="#parçalı-doğrusal-regresyon"><span class="toc-section-number">4.4</span>  Parçalı Doğrusal Regresyon</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Nitel Açıklayıcı Değişkenli Regresyon Modelleri</span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="ücret-modeli" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="ücret-modeli"><span class="header-section-number">4.1</span> Ücret Modeli</h2>
<p>Saatlik ücreti (dolar bazında) belirleyen faktörleri örneklemde araştırmak üzere, Mart 1995’te görüşme yapılan 1289 kişilik (anakütleden alınan örneklem) bir yatay-kesite bakmış ve bir regresyon modeli kurmuştuk. Burada kullandığımız kukla değişkenler aşağıdaki gibi gösterilebilir.</p>
<p><span class="math inline">\(Wage_i = \beta_1 + \beta_2D_{2i} + \beta_3D_{3i} + \beta_4D_{4i} + \beta_5Educ_i + \beta_6Exper_i + \epsilon_i\)</span></p>
<p>Yukarıdaki modelde D’ler kukla (dummy) değişkenlerdir.</p>
<p><span class="math inline">\(D_{2i}:\)</span> Kadın 1, Erkek 0</p>
<p><span class="math inline">\(D_{3i}:\)</span> Beyaz Değil 1, Beyaz 0</p>
<p><span class="math inline">\(D_{4i}:\)</span> Sendikalı 1, Sendikasız 0</p>
<p>Kukla değişkenler söz konusu olduğu zaman aşağıdaki değerlendirmeler dikkate alınmalıdır.</p>
<ul>
<li>Eğer modele kesme terimi dahil edilmiş ise kukla değişken sayısının 1 eksiği kadar kukla değişken belirlenir. Yani, m kategori varsa (m-1) kukla değişken belirlenir.</li>
</ul>
<p>Yukarıdaki değerlendirme dikkate alınmazsa kukla değişken tuzağı denilen duruma düşülür ki bu da tam doğrusal bağlantı durumudur. Örneğin, 3 kategori için 3 kukla değişken ve bir de kesme terimi olsun. Üç kukla değişkenin toplamı 1 olacaktır. Bu değer ise 1 olan ortak kesme terimine eşit olacaktır. Buna tam doğrusallık denir.</p>
<ul>
<li><p>Eğer tüm kategoriler kukla değişken olarak dahil edilmek isteniyorsa bir önceki maddede bahsedilen kukla değişken tuzağından kurtulmak için kesme terimi modelden çıkarılmalıdır.</p></li>
<li><p>Bir kategori 0 değerini alıyorsa (kadın 1; erkek 0 gibi) referans, gösterge ya da karşılaştırma kategorisi ismini alır.</p></li>
<li><p>Kukla değişkenlerin (1 ve 0 olarak belirlendiğinde) logaritması alınmamalıdır.</p></li>
</ul>
<p>Kukla değişkenleri yorumlamadan önce model çıktısını hatırlayalım.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggthemes)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(zoo)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">#library(segmented)</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"./data/drm.xls"</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&lt;&gt;%</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(wage, female, nonwhite, union, education, exper)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> wage <span class="sc">~</span> female <span class="sc">+</span> nonwhite <span class="sc">+</span> union <span class="sc">+</span> education <span class="sc">+</span> exper, <span class="at">data =</span> df)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wage ~ female + nonwhite + union + education + exper, 
    data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-20.781  -3.760  -1.044   2.418  50.414 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -7.18334    1.01579  -7.072 2.51e-12 ***
female      -3.07488    0.36462  -8.433  &lt; 2e-16 ***
nonwhite    -1.56531    0.50919  -3.074  0.00216 ** 
union        1.09598    0.50608   2.166  0.03052 *  
education    1.37030    0.06590  20.792  &lt; 2e-16 ***
exper        0.16661    0.01605  10.382  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.508 on 1283 degrees of freedom
Multiple R-squared:  0.3233,    Adjusted R-squared:  0.3207 
F-statistic: 122.6 on 5 and 1283 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Diğer tüm değişkenler sabit tutulduğunda;</p>
<ul>
<li><p>female: Bir kadın işçinin ortalama saatlik ücreti bir erkek işçinin ortalama saatlik ücretine göre $3.07 daha düşüktür. Referans kategori erkektir.</p></li>
<li><p>nonwhite: Beyaz olmayan bir işçinin ortalama saatlik ücreti beyaz olan bir işçinin ortalama saatlik ücretine göre $1.56 daha düşüktür. Referans kategori beyaz.</p></li>
<li><p>union: Sendikalı bir işçinin ortalama saatlik ücreti sendikasız bir işçinin ortalama saatlik ücretine göre $1.09 daha düşüktür. Referans kategori sendikasız.</p></li>
</ul>
<p>Tüm p’ler neredeyse sıfır olduğu için kukla parametrelerinin tamamı istatistiksel olarak anlamlıdır.</p>
<p>-7.18 olan ortak kesme değeri, 0 değeri alan kategorileri temsil eder. Beyaz, sendikasız ve erkek işçi için beklenen saatlik ücrettir denilebilir.</p>
</section>
<section id="yapısal-değişimdeki-rolü" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="yapısal-değişimdeki-rolü"><span class="header-section-number">4.2</span> Yapısal Değişimdeki Rolü</h2>
<p>1959 - 2007 dönemi için ABD’de brüt özel yatırımlar (GPI) ile brüt özel tasarruflar (GPS) arasındaki ilişkiye bakalım. İlgili verilere <em>kd1.xls</em> dosyasından ulaşılabilir.</p>
<p>Yatırım fonksiyonu:</p>
<p><span class="math inline">\(GPI_t = \beta_1 + \beta_2GPS_t + \epsilon_t, \beta_2 &gt; 0\)</span></p>
<p>Herhangi bir yapısal kırılma olup olmadığı değerlendirmesine girmeden model aşağıdaki gibi kurulsun.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"./data/kd1.xls"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(obs,gpi,gps)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>model_yapisal_normal <span class="ot">&lt;-</span> <span class="fu">lm</span>(gpi <span class="sc">~</span> gps, <span class="at">data =</span> df1)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_yapisal_normal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = gpi ~ gps, data = df1)

Residuals:
    Min      1Q  Median      3Q     Max 
-275.06  -65.89   29.12   55.31  336.84 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -78.72105   27.48474  -2.864  0.00623 ** 
gps           1.10740    0.02908  38.081  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 114.9 on 47 degrees of freedom
Multiple R-squared:  0.9686,    Adjusted R-squared:  0.9679 
F-statistic:  1450 on 1 and 47 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>GPS $1 arttığında ortalama GPI $1.1 artmaktadır.</p>
<p>Peki, yapısal kırılma var mıdır?</p>
<p>1981’den itibaren olan gözlemler için 1 değerini alan kategori Recession81 olsun. Bu durumda 1981 öncesi de 0 değerini alacaktır.</p>
<p><span class="math inline">\(GPI_t = \beta_1 + \beta_2GPS_t + \beta_3Recession81_t + \epsilon_t\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>df1 <span class="sc">%&lt;&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">recession81 =</span> <span class="fu">ifelse</span>(</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>        obs <span class="sc">&gt;=</span> <span class="dv">1981</span>, <span class="dv">1</span>, <span class="dv">0</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>model_yapisal_81 <span class="ot">&lt;-</span> <span class="fu">lm</span>(gpi <span class="sc">~</span> gps <span class="sc">+</span> recession81, <span class="at">data =</span> df1)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_yapisal_81)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = gpi ~ gps + recession81, data = df1)

Residuals:
    Min      1Q  Median      3Q     Max 
-228.98  -42.82    0.73   37.82  340.56 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -83.48603   23.15913  -3.605 0.000765 ***
gps            1.28867    0.04707  27.380  &lt; 2e-16 ***
recession81 -240.78785   53.39663  -4.509 4.46e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 96.69 on 46 degrees of freedom
Multiple R-squared:  0.9782,    Adjusted R-squared:  0.9773 
F-statistic:  1034 on 2 and 46 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>-240.78 olan kukla parametresi istatistiksel olarak anlamlıdır. Resesyon öncesi dönem ise (-83.48 - 240.78) = -324.26’dır.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>df1 <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(<span class="sc">-</span>recession81) <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pivot_longer</span>(<span class="sc">!</span>obs, <span class="at">names_to =</span> <span class="st">"vars"</span>, <span class="at">values_to =</span> <span class="st">"vals"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> obs, <span class="at">y =</span> vals, <span class="at">color =</span> vars)) <span class="sc">+</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">1981</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_fivethirtyeight</span>() <span class="sc">+</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="fu">theme</span>(<span class="at">legend.title =</span> <span class="fu">element_blank</span>()) <span class="sc">+</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"red"</span>,<span class="st">"blue"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="kukla_degisken_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="mevsimsel-verilerdeki-rolü" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="mevsimsel-verilerdeki-rolü"><span class="header-section-number">4.3</span> Mevsimsel Verilerdeki Rolü</h2>
<p>Mevsime duyarlı olan moda giyim satışlarına bakalım. İlgili verilere <em>kd2.xls</em> dosyasından ulaşılabilir.</p>
<p>Model aşağıdaki gibi olsun.</p>
<p><span class="math inline">\(Sales_t = \beta_1 + \beta_2D_{2t} + \beta_3D_{3t} + \beta_4D_{4t} + \epsilon_t\)</span></p>
<p><span class="math inline">\(D_2:\)</span> İkinci çeyrek için 1</p>
<p><span class="math inline">\(D_3:\)</span> Üçüncü çeyrek için 1</p>
<p><span class="math inline">\(D_4:\)</span> Dördüncü çeyrek için 1</p>
<p><span class="math inline">\(Sales:\)</span> Bin fit-karelik perakende alanı başına reel satış</p>
<p><span class="math inline">\(\beta_1:\)</span> Birinci çeyrek ortalama satış değeri</p>
<p>İlk çeyrek referans çeyrektir.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"./data/kd2.xls"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(obs,sales) <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">obs =</span> <span class="fu">as.yearqtr</span>(<span class="fu">gsub</span>(<span class="st">":"</span>,<span class="st">"-"</span>,obs))</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df2, <span class="fu">aes</span>(<span class="at">x =</span> obs, <span class="at">y =</span> sales)) <span class="sc">+</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_fivethirtyeight</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="kukla_degisken_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>df2 <span class="sc">%&lt;&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">quarter =</span> <span class="fu">substr</span>(obs,<span class="dv">6</span>,<span class="dv">7</span>),</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"q1"</span> <span class="ot">=</span> <span class="fu">ifelse</span>(quarter <span class="sc">==</span> <span class="st">"Q1"</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"q2"</span> <span class="ot">=</span> <span class="fu">ifelse</span>(quarter <span class="sc">==</span> <span class="st">"Q2"</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"q3"</span> <span class="ot">=</span> <span class="fu">ifelse</span>(quarter <span class="sc">==</span> <span class="st">"Q3"</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"q4"</span> <span class="ot">=</span> <span class="fu">ifelse</span>(quarter <span class="sc">==</span> <span class="st">"Q4"</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>model_mevsim <span class="ot">&lt;-</span> <span class="fu">lm</span>(sales <span class="sc">~</span> q2 <span class="sc">+</span> q3 <span class="sc">+</span> q4, <span class="at">data =</span> df2)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_mevsim)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sales ~ q2 + q3 + q4, data = df2)

Residuals:
    Min      1Q  Median      3Q     Max 
-21.740  -5.511   1.340   7.193  17.587 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   73.183      3.977  18.399 1.18e-15 ***
q2            14.692      5.625   2.612   0.0153 *  
q3            27.965      5.625   4.971 4.47e-05 ***
q4            57.115      5.625  10.154 3.65e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 10.52 on 24 degrees of freedom
Multiple R-squared:  0.8235,    Adjusted R-squared:  0.8014 
F-statistic: 37.32 on 3 and 24 DF,  p-value: 3.372e-09</code></pre>
</div>
</div>
<ul>
<li><p><span class="math inline">\(D_2:\)</span> İkinci çeyrekteki ortalama satış değeri referans çeyrekteki ortalama satıştan 14.692 birim daha yüksektir. İkinci çeyrek ortalama satış değeri = 73.183 + 14.692 = 87.875’tir.</p></li>
<li><p><span class="math inline">\(D_3:\)</span> Üçüncü çeyrekteki ortalama satış değeri referans çeyrekteki ortalama satıştan 27.965 birim daha yüksektir. Üçüncü çeyrek ortalama satış değeri = 73.183 + 27.965 = 101.148’tir.</p></li>
<li><p><span class="math inline">\(D_4:\)</span> Dördüncü çeyrekteki ortalama satış değeri referans çeyrekteki ortalama satıştan 57.115 birim daha yüksektir. Dördüncü çeyrek ortalama satış değeri = 73.183 + 57.115 = 130.298’tir.</p></li>
</ul>
<p>p değerlerine göre kukla parametreleri istatistiksel olarak anlamlıdır.</p>
<p>Mevsimsel etkiden arındırmak için aşağıdaki yol izlenebilir:</p>
<ol type="i">
<li><p>Tahmin edilen modelden satış hacmi tahmini bulunur.</p></li>
<li><p>Gerçek satış hacminden tahmin edilen satış değeri çıkartılır ve kalıntılar elde edilir.</p></li>
<li><p>Örneklem ortalama satış değeri elde edilen kalıntılara eklenir.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>df2 <span class="sc">%&lt;&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">f_sales =</span> model_mevsim<span class="sc">$</span>fitted.values,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">resid =</span> sales <span class="sc">-</span> f_sales,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">seadj =</span> <span class="fu">mean</span>(sales) <span class="sc">+</span> resid</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>df2 <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(obs,sales,seadj) <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pivot_longer</span>(<span class="sc">!</span>obs, <span class="at">names_to =</span> <span class="st">"vars"</span>, <span class="at">values_to =</span> <span class="st">"vals"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> obs, <span class="at">y =</span> vals, <span class="at">color =</span> vars)) <span class="sc">+</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_fivethirtyeight</span>() <span class="sc">+</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="fu">theme</span>(<span class="at">legend.title =</span> <span class="fu">element_blank</span>()) <span class="sc">+</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"red"</span>,<span class="st">"blue"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="kukla_degisken_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="parçalı-doğrusal-regresyon" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="parçalı-doğrusal-regresyon"><span class="header-section-number">4.4</span> Parçalı Doğrusal Regresyon</h2>
<p>Hipotetik olarak bir üreticinin birim başına ortalama maliyeti (ac) ile üretim partisi büyüklüğüne (lot_size) bakalım. İlgili verilere <em>kd3.xlsx</em> dosyasından ulaşılabilir.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>df3 <span class="ot">&lt;-</span> readxl<span class="sc">::</span><span class="fu">read_excel</span>(<span class="st">"./data/kd3.xlsx"</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df3, <span class="fu">aes</span>(<span class="at">x =</span> lot_size, <span class="at">y =</span> ac)) <span class="sc">+</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_fivethirtyeight</span>() <span class="sc">+</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Parti Büyüklüğü"</span>,</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Ortalama Maliyet"</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="kukla_degisken_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Yukarıdaki görselde parti büyüklüğü 200 öncesi ve sonrası için farklı doğruların çalıştırılabileceği düşünülebilir. Yani, 200 eşik değerdir.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>model_parcali <span class="ot">&lt;-</span> <span class="fu">lm</span>(ac <span class="sc">~</span> lot_size, <span class="at">data =</span> df3)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>segmented_model_parcali <span class="ot">&lt;-</span> segmented<span class="sc">::</span><span class="fu">segmented</span>(</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    model_parcali, <span class="at">seg.Z =</span> <span class="sc">~</span>lot_size, <span class="at">psi =</span> <span class="dv">200</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(segmented_model_parcali)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    ***Regression Model with Segmented Relationship(s)***

Call: 
segmented.lm(obj = model_parcali, seg.Z = ~lot_size, psi = 200)

Estimated Break-Point(s):
                  Est. St.Err
psi1.lot_size 195.766 10.524

Meaningful coefficients of the linear terms:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 15.313000   0.753708  20.317 1.75e-07 ***
lot_size    -0.051750   0.005277  -9.807 2.43e-05 ***
U1.lot_size  0.039664   0.006615   5.996       NA    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3337 on 7 degrees of freedom
Multiple R-Squared: 0.9833,  Adjusted R-squared: 0.9762 

Boot restarting based on 6 samples. Last fit:
Convergence attained in 2 iterations (rel. change 2.359e-12)</code></pre>
</div>
</div>
<p>Kullanılan fonksiyon x = 195.766’da bir kırılma tespit etti.</p>
<p>Eğer x <span class="math inline">\(\leq\)</span> 195.766 ise;</p>
<p>y = 15.313 - 0.052 * lot_size</p>
<p>Eğer x <span class="math inline">\(&gt;\)</span> 195.766 ise;</p>
<p>(15.313 - 0.052 * 195.766) + (-0.052 + 0.0396) * (lot_size-195.766)</p>
<p>5.133 - 0.0124 * (lot_size-195.766)</p>
<p>195.766 birimlik parti büyüklüğüne kadar parti büyüklüğündeki birim artış başına birim maliyet 5 kuruş azalıyor. 195.766 birimlik parti büyüklüğünden sonra ise yaklaşık 1 kuruş azalıyor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>df3 <span class="sc">%&lt;&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">pr =</span> segmented_model_parcali<span class="sc">$</span>fitted.values</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df3) <span class="sc">+</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> lot_size, <span class="at">y =</span> ac)) <span class="sc">+</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> lot_size, <span class="at">y =</span> pr), <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_fivethirtyeight</span>() <span class="sc">+</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Parti Büyüklüğü"</span>,</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Ortalama Maliyet"</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="kukla_degisken_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./regresyon_model_fonksiyon.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regresyon Modellerinin Fonksiyon Yapıları</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./kaynak.html" class="pagination-link">
        <span class="nav-page-text">Yararlandığım Kaynaklar</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>