<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>R ile Uygulamalı Ekonometri - 3&nbsp; Regresyon Modellerinin Fonksiyon Yapıları</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./kukla_degisken.html" rel="next">
<link href="./francis_galton_regresyon.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regresyon Modellerinin Fonksiyon Yapıları</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">R ile Uygulamalı Ekonometri</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Önsöz</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./surec.html" class="sidebar-item-text sidebar-link">Süreç</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./veriseti.html" class="sidebar-item-text sidebar-link">Veri Setleri</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./kutuphane.html" class="sidebar-item-text sidebar-link">Kütüphaneler</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dogrusal_regresyon_modeli.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Doğrusal Regresyon Modeli</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./francis_galton_regresyon.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Francis Galton ve Regresyon Terimi</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regresyon_model_fonksiyon.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regresyon Modellerinin Fonksiyon Yapıları</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./kukla_degisken.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Nitel Açıklayıcı Değişkenli Regresyon Modelleri</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./kaynak.html" class="sidebar-item-text sidebar-link">Yararlandığım Kaynaklar</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#log-log" id="toc-log-log" class="nav-link active" data-scroll-target="#log-log"><span class="toc-section-number">3.1</span>  Log-Log</a>
  <ul class="collapse">
  <li><a href="#uygulama" id="toc-uygulama" class="nav-link" data-scroll-target="#uygulama"><span class="toc-section-number">3.1.1</span>  Uygulama</a></li>
  </ul></li>
  <li><a href="#log-lin" id="toc-log-lin" class="nav-link" data-scroll-target="#log-lin"><span class="toc-section-number">3.2</span>  Log-Lin</a>
  <ul class="collapse">
  <li><a href="#uygulama-1" id="toc-uygulama-1" class="nav-link" data-scroll-target="#uygulama-1"><span class="toc-section-number">3.2.1</span>  Uygulama</a></li>
  <li><a href="#ek-doğrusal-trend-modeli" id="toc-ek-doğrusal-trend-modeli" class="nav-link" data-scroll-target="#ek-doğrusal-trend-modeli"><span class="toc-section-number">3.2.2</span>  Ek: Doğrusal Trend Modeli</a></li>
  </ul></li>
  <li><a href="#lin-log" id="toc-lin-log" class="nav-link" data-scroll-target="#lin-log"><span class="toc-section-number">3.3</span>  Lin-Log</a>
  <ul class="collapse">
  <li><a href="#uygulama-2" id="toc-uygulama-2" class="nav-link" data-scroll-target="#uygulama-2"><span class="toc-section-number">3.3.1</span>  Uygulama</a></li>
  </ul></li>
  <li><a href="#ters-model" id="toc-ters-model" class="nav-link" data-scroll-target="#ters-model"><span class="toc-section-number">3.4</span>  Ters Model</a>
  <ul class="collapse">
  <li><a href="#uygulama-3" id="toc-uygulama-3" class="nav-link" data-scroll-target="#uygulama-3"><span class="toc-section-number">3.4.1</span>  Uygulama</a></li>
  </ul></li>
  <li><a href="#polinom-regresyon" id="toc-polinom-regresyon" class="nav-link" data-scroll-target="#polinom-regresyon"><span class="toc-section-number">3.5</span>  Polinom Regresyon</a>
  <ul class="collapse">
  <li><a href="#uygulama-4" id="toc-uygulama-4" class="nav-link" data-scroll-target="#uygulama-4"><span class="toc-section-number">3.5.1</span>  Uygulama</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regresyon Modellerinin Fonksiyon Yapıları</span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<p>Klasik Doğrusal Regresyon Modeli’nin varsayımlarından birisi şöyleydi:</p>
<ul>
<li>Regresyon modeli parametreler açısından doğrusaldır. Y ve X değişkenlerine göre ise doğrusallık aranmaz.</li>
</ul>
<p>Parametreler açısından doğrusallık: Parametrelerin kuvveti alınmamış (<span class="math inline">\(\beta_2^2\)</span> gibi), parametreler diğer parametrelere bölünmemiş (<span class="math inline">\(\beta_2 / \beta_3\)</span> gibi) veya dönüştürülmemiştir (<span class="math inline">\(ln\beta_4\)</span> gibi).</p>
<p>Değişkenler açısından: Koşul aranmaz. Örneğin, X değişkeninin doğal logaritması (<span class="math inline">\(lnX_2\)</span> gibi), tersi (<span class="math inline">\(1/X_3\)</span> gibi) veya kuvveti (<span class="math inline">\(X_2^3\)</span> gibi) alınmış olabilir.</p>
<p>Bu başlıkta, parametrelere göre doğrusal olan ancak değişkenlere göre doğrusal olup olmamasının bir önemi olmayan modelleri ele alacağız.</p>
<section id="log-log" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="log-log"><span class="header-section-number">3.1</span> Log-Log</h2>
<p>Log-Log, hem bağımlı değişkenin hem de açıklayıcı değişkenlerin logaritmik yapıda olduğu bir fonksiyon kalıbı türüdür.</p>
<p>Üstel regresyon modelini inceleyelim.</p>
<p><span class="math inline">\(Y_i = \beta_1X_i^{\beta_2}e^{\epsilon_i}\)</span></p>
<p>Yukarıdaki model doğal logaritması alınarak şöyle yazılabilir:</p>
<p><span class="math inline">\(lnY_i = ln\beta_1 + \beta_2lnX_i + \epsilon_i\)</span></p>
<p>Son olarak aşağıdaki forma çevirebiliriz.</p>
<p><span class="math inline">\(lnY_i = \alpha + \beta_2lnX_i + \epsilon_i\)</span></p>
<p>Cobb-Douglas fonksiyonu ile devam edelim.</p>
<p><span class="math inline">\(Q_i = \beta_1L_i^{\beta_2}K_i^{\beta_3}\)</span></p>
<p><span class="math inline">\(Q:\)</span> Çıktı</p>
<p><span class="math inline">\(L:\)</span> Emek Girdisi</p>
<p><span class="math inline">\(K:\)</span> Sermaye</p>
<p><span class="math inline">\(\beta_1:\)</span> Sabit</p>
<p>Yukarıdaki model parametreler açısından doğrusal değildir ki bu da doğrusal olmayan yöntemler ile ilerlenmesini gerektirir. Peki, (doğal) logaritmasını alırsak tam da varsayımda istediğimiz gibi parametreler açısından doğrusal olabilir mi?</p>
<p><span class="math inline">\(lnQ_i = ln\beta_1 + \beta_2lnL_i + \beta_3lnK_i\)</span></p>
<p><span class="math inline">\(ln\beta_1\)</span>’e A dersek;</p>
<p><span class="math inline">\(lnQ_i = A + \beta_2lnL_i + \beta_3lnK_i\)</span> olur. Yazılan eşitlik;</p>
<ul>
<li><p><span class="math inline">\(Q\)</span>, <span class="math inline">\(L\)</span> ve <span class="math inline">\(K\)</span> değişkenleri açısından doğrusal değildir</p></li>
<li><p><span class="math inline">\(A\)</span>, <span class="math inline">\(\beta_2\)</span> ve <span class="math inline">\(\beta_3\)</span> parametrelerine göre doğrusaldır</p></li>
</ul>
<p>Hata terimi <span class="math inline">\(\epsilon_i\)</span> de eklenirse doğrusal regresyon modelinin son hali elde edilir.</p>
<p><span class="math inline">\(lnQ_i = A + \beta_2lnL_i + \beta_3lnK_i + \epsilon_i\)</span></p>
<section id="uygulama" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="uygulama"><span class="header-section-number">3.1.1</span> Uygulama</h3>
<p>ABD için Cobb-Douglas fonksiyonuna bakalım. İlgili verilere <em>rmfk1.xls</em> dosyası ile ulaşılabilir.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggthemes)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"./data/rmfk1.xls"</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>df1 <span class="sc">%&lt;&gt;%</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(output,labor,capital)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Bağımlı değişken:</p>
<ul>
<li><strong>output:</strong> ABD imalat sektörüne ait çıktı (katma değerle ölçülmüş, bin dolar)</li>
</ul>
<p>Bağımsız değişkenler:</p>
<ul>
<li><p><strong>labor:</strong> Emek girdisi (çalışma saati, bin saat)</p></li>
<li><p><strong>capital:</strong> Sermaye girdisi (sermaye harcaması, bin dolar)</p></li>
</ul>
<p>Değişkenleri logaritmik yapıda yazalım.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df1 <span class="sc">%&lt;&gt;%</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">ln_output =</span> <span class="fu">log</span>(output),</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">ln_labor =</span> <span class="fu">log</span>(labor),</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">ln_capital =</span> <span class="fu">log</span>(capital)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Model kurulabilir.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>loglog_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(ln_output <span class="sc">~</span> ln_labor <span class="sc">+</span> ln_capital, <span class="at">data =</span> df1)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(loglog_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ln_output ~ ln_labor + ln_capital, data = df1)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.45645 -0.12112 -0.05319  0.04518  1.21579 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  3.88760    0.39623   9.812 4.70e-13 ***
ln_labor     0.46833    0.09893   4.734 1.98e-05 ***
ln_capital   0.52128    0.09689   5.380 2.18e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2668 on 48 degrees of freedom
Multiple R-squared:  0.9642,    Adjusted R-squared:  0.9627 
F-statistic: 645.9 on 2 and 48 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><span class="math inline">\(Q_i = 48.79L^{0.47}K^{0.52}\)</span></p>
<p>Sabit değer 3.8876’nın ters logaritması yaklaşık olarak 48.79’dur.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">as.numeric</span>(<span class="fu">coef</span>(loglog_model)[<span class="dv">1</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 48.79362</code></pre>
</div>
</div>
<p>Yukarıdaki model çıktısının yorumları şöyledir:</p>
<ul>
<li><p>Çok küçük p değerlerine sahip regresyon parametreleri bireysel açıdan istatistiksel olarak anlamlıdır.</p></li>
<li><p>F istatistiğine ait p değeri çok küçük olduğu için model istatistiksel olarak anlamlıdır.</p></li>
<li><p>0.96 gibi çok yüksek bir <span class="math inline">\(R^2\)</span> sevindirici olmak ile beraber bir soru işareti de yaratabilir.</p></li>
<li><p>Log-Log modellerde eğim parametreleri esneklik olarak yorumlanabilir. Aynı zamanda ölçüm birimleri ortadan kalkar ve yüzde değişim altında değerlendirilirler.</p></li>
</ul>
<p>Sermaye girdisi (ln_capital) sabit iken, emek girdisi (ln_labor) %1 artırılırsa imalat sektörüne ait çıktı ortalamada %0.47 artar.</p>
<p>Emek girdisi (ln_labor) sabit iken, sermaye girdisi (ln_capital) %1 artırılırsa imalat sektörüne ait çıktı ortalamada %0.52 artar.</p>
</section>
</section>
<section id="log-lin" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="log-lin"><span class="header-section-number">3.2</span> Log-Lin</h2>
<p>Bağımlı değişkenin logaritmik; diğer açıklayıcı değişkenlerin düzey ya da doğrusal yapıda olduğu bir fonksiyon kalıbı türüdür.</p>
<p>Bileşik faiz formülünü anımsayalım.</p>
<p><span class="math inline">\(Y_t = Y_0(1+r)^t\)</span></p>
<p>r, Y’nin bileşik (zaman içindeki) büyüme hızıdır.</p>
<p>Eşitliğin logaritmasını alalım.</p>
<p><span class="math inline">\(lnY_t = lnY_0 + tln(1+r)\)</span></p>
<p><span class="math inline">\(lnY_0\)</span>, <span class="math inline">\(\beta_1\)</span>; <span class="math inline">\(ln(1+r)\)</span> ise <span class="math inline">\(\beta_2\)</span> olsun.</p>
<p><span class="math inline">\(lnY_t = \beta_1 + \beta_2t + \epsilon_t\)</span> olur.</p>
<p>Belli bir dönem (1998-2021 olsun) için reel GSYH’nin büyüme hızı ölçülmek isteniyorsa <span class="math inline">\(RGDP_t = RGDP_{1998}(1+r)^t\)</span> modeli kullanılabilir.</p>
<p><span class="math inline">\(RGDP:\)</span> Reel GSYH</p>
<p><span class="math inline">\(r:\)</span> Büyüme hızı</p>
<p><span class="math inline">\(t:\)</span> Kronolojik zaman</p>
<p>Her iki tarafın (doğal) logaritmasını alalım.</p>
<p><span class="math inline">\(lnRGDP_t = lnRGDP_{1998} + tln(1+r)\)</span></p>
<p><span class="math inline">\(\beta_1\)</span>, <span class="math inline">\(lnRGDP_{1998}\)</span> ve <span class="math inline">\(\beta_2\)</span>, <span class="math inline">\(ln(1+r)\)</span> olsun.</p>
<p><span class="math inline">\(lnRGDP_t = \beta_1 + \beta_2t + \epsilon_t\)</span> olur. Bu eşitlikte açıklayıcı değişken zamandır. Yani, t = 1,2,3,…,24.</p>
<section id="uygulama-1" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="uygulama-1"><span class="header-section-number">3.2.1</span> Uygulama</h3>
<p>Türkiye’nin reel GSYH büyüme hızına bakalım. Bu uygulamada, TÜİK’ten elde edilen mevsim ve takvim etkisinden arındırılmış harcama yöntemiyle GSYH, zincirlenmiş hacim endeksi kullanılacaktır. İlgili verilere <em>rmfk2.xlsx</em> dosyası ile ulaşılabilir.</p>
<p>Aşağıda açıklayıcı değişken olarak zaman değişkenini (t) ve RGDP’nin (doğal) logaritmasını ekledik.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"./data/rmfk2.xlsx"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>df2 <span class="sc">%&lt;&gt;%</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">t =</span> <span class="fu">seq</span>(<span class="dv">1</span>,<span class="fu">nrow</span>(.),<span class="dv">1</span>),</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">ln_rgdp =</span> <span class="fu">log</span>(rgdp)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Bağımlı değişken:</p>
<ul>
<li><strong>ln_rgdp:</strong> TÜİK’ten elde edilen mevsim ve takvim etkisinden arındırılmış harcama yöntemiyle GSYH, zincirlenmiş hacim endeksi</li>
</ul>
<p>Bağımsız değişken:</p>
<ul>
<li><strong>t:</strong> Zaman</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df2, <span class="fu">aes</span>(<span class="at">x =</span> t, <span class="at">y =</span> ln_rgdp)) <span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_fivethirtyeight</span>() <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Türkiye Reel GSYH'sinin Logaritması, 1998-2021"</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Kaynak: TÜİK"</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regresyon_model_fonksiyon_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Modeli kuralım.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>loglin_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(ln_rgdp <span class="sc">~</span> t, <span class="at">data =</span> df2)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(loglin_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ln_rgdp ~ t, data = df2)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.09438 -0.02607  0.01240  0.02780  0.09694 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.11259    0.01986  207.09   &lt;2e-16 ***
t            0.04891    0.00139   35.19   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.04713 on 22 degrees of freedom
Multiple R-squared:  0.9825,    Adjusted R-squared:  0.9818 
F-statistic:  1239 on 1 and 22 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Yukarıdaki model çıktısının yorumları şöyledir:</p>
<ul>
<li><p>Çok küçük p değerlerine sahip regresyon parametreleri bireysel açıdan istatistiksel olarak anlamlıdır.</p></li>
<li><p>F istatistiğine ait p değeri çok küçük olduğu için model istatistiksel olarak anlamlıdır.</p></li>
<li><p>Büyüme hızını hesaplamak için <span class="math inline">\(\beta_2\)</span> 100 ile çarpılır. Model, 1998-2021 döneminde Türkiye reel GSYH’sinin yıllık %4.9 oranında artmış olduğunu gösteriyor. 35.19 tahmin edilen t değeri istatistiksel açıdan oldukça anlamlıdır. Bu da aynı zamanda büyüme hızının anlamlı olduğunu gösterir.</p></li>
<li><p>Kesme terimi 4.11’in ters logaritması 61.11’dir. Bu da aşağı yukarı 1998’e ait değerdir.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>df2<span class="sc">$</span>rgdp[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 70.7</code></pre>
</div>
</div>
<p><span class="math inline">\(\beta_2\)</span> parametresi bileşik büyüme hızı r’yi değil; anlık büyüme hızını verir. Eğer <span class="math inline">\(r = exp(\beta_2)-1\)</span> yapılırsa bileşik büyüme hızına ulaşılır.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">as.numeric</span>(<span class="fu">coef</span>(loglin_model)[<span class="dv">2</span>])) <span class="sc">-</span> <span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.05012937</code></pre>
</div>
</div>
<p>Yani, yaklaşık %5.1’dir. Bileşim olması sebebiyle anlık büyüme hızı %4.9’dan biraz daha fazla hesaplanmıştır.</p>
</section>
<section id="ek-doğrusal-trend-modeli" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="ek-doğrusal-trend-modeli"><span class="header-section-number">3.2.2</span> Ek: Doğrusal Trend Modeli</h3>
<p>Yukarıdaki büyüme modeli yerine doğrusal trend modeli ile tahmin etmek istediğimizi varsayalım.</p>
<p><span class="math inline">\(RGDP_t = \beta_1 + \beta_2zaman + \epsilon_t\)</span></p>
<p>Yukarıdaki eşitlikte, <span class="math inline">\(\beta_2\)</span> eğim parametresi birim dönemde RGDP’deki mutlak değişimi verir. <span class="math inline">\(\beta_2\)</span> pozitif ise RGDP’de (farklı bir değişken de olabilirdi) yükselen bir trend vardır. Tam tersi, negatif ise azalan bir trend anlamına gelecektir.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>dtrend_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(rgdp <span class="sc">~</span> t, <span class="at">data =</span> df2)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dtrend_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = rgdp ~ t, data = df2)

Residuals:
     Min       1Q   Median       3Q      Max 
-16.4597  -3.4598  -0.7431   3.3737  17.1847 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  47.7931     3.3730   14.17 1.54e-12 ***
t             5.7222     0.2361   24.24  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.005 on 22 degrees of freedom
Multiple R-squared:  0.9639,    Adjusted R-squared:  0.9623 
F-statistic: 587.6 on 1 and 22 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>1998-2021 döneminde endeksin 5.7 arttığını görüyoruz. Aynı zamanda artı işaretli olması yükselen bir trendin olduğunu göstermektedir.</p>
</section>
</section>
<section id="lin-log" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="lin-log"><span class="header-section-number">3.3</span> Lin-Log</h2>
<p>Log-Lin ile açıklayıcı değişkendeki 1 birim değişime karşılık bağımlı değişkendeki yüzde büyüme ile ilgileniyorduk. Lin-Log’da ise aşağıdaki model tahmin edilir.</p>
<p><span class="math inline">\(Y_i = \beta_1 + \beta_2lnX_i + \epsilon_i\)</span></p>
<p>Yani, lin-log modellerde bağımlı değişken doğrusal yapıda iken en az bir açıklayıcı değişken logaritmik yapıdadır.</p>
<section id="uygulama-2" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="uygulama-2"><span class="header-section-number">3.3.1</span> Uygulama</h3>
<p>ABD için gıda harcamasına bakalım. İlgili verilere <em>rmfk3.xls</em> dosyası ile ulaşılabilir.</p>
<p>Aşağıda açıklayıcı değişkenin logaritmasını ekledik.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>df3 <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"./data/rmfk3.xls"</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>df3 <span class="sc">%&lt;&gt;%</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(sfdho,expend) <span class="sc">%&gt;%</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">ln_expend =</span> <span class="fu">log</span>(expend)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Bağımlı değişken:</p>
<ul>
<li><strong>sfdho:</strong> Gıda harcamasının toplam harcamadaki payı</li>
</ul>
<p>Bağımsız değişken:</p>
<ul>
<li><strong>expend:</strong> Toplam hanehalkı harcaması</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>linlog_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(sfdho <span class="sc">~</span> ln_expend, <span class="at">data =</span> df3)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linlog_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sfdho ~ ln_expend, data = df3)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.18180 -0.04350 -0.00654  0.03373  0.48594 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.930387   0.036367   25.58   &lt;2e-16 ***
ln_expend   -0.077737   0.003591  -21.65   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.06875 on 867 degrees of freedom
Multiple R-squared:  0.3509,    Adjusted R-squared:  0.3501 
F-statistic: 468.6 on 1 and 867 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Yukarıdaki model çıktısının yorumları şöyledir:</p>
<ul>
<li><p>Çok küçük p değerlerine sahip regresyon parametreleri bireysel açıdan istatistiksel olarak anlamlıdır.</p></li>
<li><p>F istatistiğine ait p değeri çok küçük olduğu için model istatistiksel olarak anlamlıdır.</p></li>
<li><p>Toplam harcama %1 arttığında gıda harcamasının toplam harcamadaki payı ortalamada 0.0008 birim düşecektir. Burada önemli bir not: Tahmin edilen eğim parametresi değeri 0.01 ile çarpılmalı ya da 100’e bölünmelidir. Yorum şöyle de yapılabilir: Toplam harcama %100 arttığında gıda harcamasının toplam harcamadaki payı ortalamada 0.08 birim azalır.</p></li>
</ul>
</section>
</section>
<section id="ters-model" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="ters-model"><span class="header-section-number">3.4</span> Ters Model</h2>
<p>Yukarıdaki örneğe ait ilişki ters olabilir mi?</p>
<p><span class="math inline">\(Y_i = \beta_1 + \beta_2 (\frac{1}{X_i}) + \epsilon_i\)</span></p>
<p><span class="math inline">\(SFDHO = \beta_1 + \beta_2 (\frac{1}{Expend_i}) + \epsilon_i\)</span></p>
<section id="uygulama-3" class="level3" data-number="3.4.1">
<h3 data-number="3.4.1" class="anchored" data-anchor-id="uygulama-3"><span class="header-section-number">3.4.1</span> Uygulama</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df3, <span class="fu">aes</span>(<span class="at">x =</span> ln_expend, <span class="at">y =</span> sfdho)) <span class="sc">+</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_fivethirtyeight</span>() <span class="sc">+</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Gıda Harcaması Payı ile Log Toplam Harcama İlişkisi"</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regresyon_model_fonksiyon_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df3, <span class="fu">aes</span>(<span class="at">x =</span> expend, <span class="at">y =</span> sfdho)) <span class="sc">+</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> y <span class="sc">~</span> <span class="fu">poly</span>(x, <span class="dv">2</span>, <span class="at">raw =</span> <span class="cn">TRUE</span>), <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_fivethirtyeight</span>() <span class="sc">+</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Gıda Harcaması Payı ile Toplam Harcama İlişkisi"</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regresyon_model_fonksiyon_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>df3 <span class="sc">%&lt;&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">ters_expend =</span> <span class="dv">1</span> <span class="sc">/</span> expend</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Modeli kuralım.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>ters_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(sfdho <span class="sc">~</span> ters_expend, <span class="at">data =</span> df3)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ters_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sfdho ~ ters_expend, data = df3)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.29889 -0.04205 -0.01120  0.03229  0.44606 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 7.726e-02  4.012e-03   19.26   &lt;2e-16 ***
ters_expend 1.331e+03  6.396e+01   20.82   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.06968 on 867 degrees of freedom
Multiple R-squared:  0.3332,    Adjusted R-squared:  0.3325 
F-statistic: 433.3 on 1 and 867 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Yukarıdaki model çıktısının yorumları şöyledir:</p>
<ul>
<li><p>Çok küçük p değerlerine sahip regresyon parametreleri bireysel açıdan istatistiksel olarak anlamlıdır.</p></li>
<li><p>F istatistiğine ait p değeri çok küçük olduğu için model istatistiksel olarak anlamlıdır.</p></li>
<li><p>Toplam harcama sonsuza gittiğinde gıda harcaması payı yaklaşık olarak %8’e yerleşecektir. Çünkü açıklayıcı değişken X sonsuza giderken <span class="math inline">\(\beta_2(1/X_i)\)</span> sıfıra yaklaşır. Y ise limit değer olan <span class="math inline">\(\beta_1\)</span>’e yaklaşır.</p></li>
<li><p><span class="math inline">\(\beta_2\)</span> eğim parametresi pozitiftir. Yani, gıda harcaması payının toplam harcamaya göre değişim hızı her noktada negatif olacaktır. Eğer <span class="math inline">\(\beta_2\)</span> negatif olsaydı bu defa her noktada pozitif olacaktı.</p></li>
</ul>
</section>
</section>
<section id="polinom-regresyon" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="polinom-regresyon"><span class="header-section-number">3.5</span> Polinom Regresyon</h2>
<section id="uygulama-4" class="level3" data-number="3.5.1">
<h3 data-number="3.5.1" class="anchored" data-anchor-id="uygulama-4"><span class="header-section-number">3.5.1</span> Uygulama</h3>
<p>Türkiye’nin reel GSYH’si için aşağıdaki modele bakalım.</p>
<p><span class="math inline">\(RGDP_t = \beta_1 + \beta_2zaman + \beta_3zaman^2 + \epsilon_t\)</span></p>
<p>Yukarıdaki eşitlik zaman değişkenine göre karesel fonksiyon ya da ikinci derece polinomdur. Eğer bu modele <span class="math inline">\(zaman^3\)</span> eklenseydi üçüncü derece bir polinom denklemi olacaktı. Kısaca, açıklayıcı değişkenin en büyük kuvveti polinomun derecesine eşittir.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>df2 <span class="sc">%&lt;&gt;%</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">t2 =</span> t<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Modeli kuralım.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>polinom2_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(rgdp <span class="sc">~</span> t <span class="sc">+</span> t2, <span class="at">data =</span> df2)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(polinom2_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = rgdp ~ t + t2, data = df2)

Residuals:
   Min     1Q Median     3Q    Max 
-9.538 -3.735  1.451  3.059  5.853 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 63.52376    3.20715  19.807 4.55e-15 ***
t            2.09207    0.59110   3.539  0.00194 ** 
t2           0.14521    0.02295   6.326 2.84e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.807 on 21 degrees of freedom
Multiple R-squared:  0.9876,    Adjusted R-squared:  0.9864 
F-statistic: 834.9 on 2 and 21 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><span class="math inline">\(\frac{dRGDP}{dt} = 2.09 + 2(0.15)zaman = 2.09 + 0.3zaman\)</span></p>
<p>Yukarıda, RGDP’nin değişim hızı bu değişim hızının ölçüldüğü zamana bağlıdır. Zamana göre ikinci türev alınırsa, 0.3 değeri elde edilir. Bu da değişim hızının zaman içinde sabit olan değişim hızıdır. İkinci türev pozitif ise RGDP artan bir oranda artmaktadır.</p>
<p>Az önce tahmin edilen model yerine aşağıdaki model tahmin edilmek istensin.</p>
<p><span class="math inline">\(lnRGDP_t = \beta_1 + \beta_2t + \beta_3t^2 + \epsilon_t\)</span></p>
<p>Modeli kuralım.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>polinom2_model_l <span class="ot">&lt;-</span> <span class="fu">lm</span>(ln_rgdp <span class="sc">~</span> t <span class="sc">+</span> t2, <span class="at">data =</span> df2)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(polinom2_model_l)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ln_rgdp ~ t + t2, data = df2)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.085964 -0.032355  0.007408  0.030899  0.082041 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 4.1317305  0.0317325 130.205  &lt; 2e-16 ***
t           0.0444972  0.0058485   7.608 1.82e-07 ***
t2          0.0001766  0.0002271   0.778    0.445    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.04756 on 21 degrees of freedom
Multiple R-squared:  0.983, Adjusted R-squared:  0.9814 
F-statistic: 608.5 on 2 and 21 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><span class="math inline">\(\frac{dlnRGDP}{dt} = \beta_2 + 2\beta_3t\)</span></p>
<p><span class="math inline">\(\frac{1}{RGDP} \frac{dRGDP}{dt} = \beta_2 + 2\beta_3t\)</span></p>
<p>RGDP’nin büyüme hızı = <span class="math inline">\(\beta_2 + 2\beta_3t = 0.044 + 0.0002t\)</span></p>
<p>RGDP’nin büyüme hızı birim zaman başına 0.0002 oranında artmaktadır.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./francis_galton_regresyon.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Francis Galton ve Regresyon Terimi</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./kukla_degisken.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Nitel Açıklayıcı Değişkenli Regresyon Modelleri</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>